import streamlit as st

def render_critic_view(state: dict):
    verdict = state.get("critic_verdict", "FLAGGED")
    reasoning = state.get("critic_reasoning", "No reasoning provided.")
    flags = state.get("critic_flags", [])
    confidence_adj = state.get("critic_confidence_adjustment", "MAINTAINED")
    
    st.subheader("Critic Agent Review")
    
    # Verdict Badge
    if verdict == "APPROVED":
        st.success(f"**Verdict: {verdict}**")
    elif verdict == "REJECTED":
        st.error(f"**Verdict: {verdict}**")
    else:
        st.warning(f"**Verdict: {verdict}**")
        
    # Confidence pill
    if confidence_adj == "UPGRADED":
        st.markdown("Confidence Adjustment: 🟢 **UPGRADED** ⬆️")
    elif confidence_adj == "DOWNGRADED":
        st.markdown("Confidence Adjustment: 🔴 **DOWNGRADED** ⬇️")
    else:
        st.markdown("Confidence Adjustment: ⚪ **MAINTAINED**")
        
    # Reasoning blockquote
    st.markdown(f"> *{reasoning}*")
    
    # Flags
    if flags:
        st.markdown("**Flags Identified:**")
        for flag in flags:
            st.markdown(f"- 🔴 {flag}")
            
    st.caption("Critic Agent output is advisory. It is generated by an LLM and may be incorrect.")
